### ISSUE TITLE
Get zephyr devices to communicate with webpage

### ISSUE THREAD

**Issue by MayaCutkosky** [clarkwalcott/Zephyr-Group9#1]
Need to have better understanding of the net zephyr functions. Perhaps get them to communicate with our website.

**Comment by skitzobrownie** [comment]
progress has been made, but new road bumps have arrived. Additional issues have been opened in response to this.

**Comment by skitzobrownie** [comment]
We were able to get Zephyr running on a ubuntu system, but due to the complications we had initially with our Macs we weren't able to fully implement the net_tools communication for devices.
