### ISSUE TITLE
use SQL commands to have AJAX requests display on EC2

### ISSUE THREAD

**Issue by skitzobrownie** [clarkwalcott/Zephyr-Group9#4]

**Comment by skitzobrownie** [comment]
<img width="1130" alt="ajaxRequest" src="https://user-images.githubusercontent.com/34043204/56930235-9d216080-6aa1-11e9-880d-78177fd1e11b.png">
Need to add functionality to this image above. Replacing the never-ending "loading" with content.

**Comment by skitzobrownie** [comment]
We have found a way to connect our zephyr OS to the internet, but command line issues have arrived and new issues have been created

**Comment by clarkwalcott** [comment]
The AJAX commands are working and update the content box to show that something happened. We were unable to connect zephyr to it at this time though.
