### ISSUE TITLE
Allow Admin to add/modify/delete users

### ISSUE THREAD

**Issue by clarkwalcott** [clarkwalcott/Zephyr-Group9#7]
Use sql commands through buttons on the admin's user pages. Make sure the user relation must have at least one admin user and admin users can only be deleted by other admins.

**Comment by sgoggins** [comment]
Login is the lowest priority, in my opinion. But your group can decide!

**Comment by clarkwalcott** [comment]
Currently, admin can add users (not additional admins). Adds buttons to user page (through database)

**Comment by skitzobrownie** [comment]
This has all been implemented on our EC2 instance, and is this functionality is only usable as admin. (like the issues states)
