### ISSUE TITLE
populate user page/ homepage with buttons

### ISSUE THREAD

**Issue by skitzobrownie** [clarkwalcott/Zephyr-Group9#9]
The buttons will be for each user that is created, and will allow them to go to the page they desire.

**Comment by skitzobrownie** [comment]
<img width="1641" alt="addButtons" src="https://user-images.githubusercontent.com/34043204/57100676-32606700-6ce5-11e9-8091-0db8ba097eff.png">
here is where the buttons will be added

**Comment by skitzobrownie** [comment]
seems to be related to query problems we are having

**Comment by clarkwalcott** [comment]
![userPage](https://user-images.githubusercontent.com/9795518/57201846-df481780-6f63-11e9-86f1-eebc2145b225.png)
Works. Grabs usernames from database and creates a button for each one. Links to login page and only allows the user to login using the name of the button they clicked
